### ISSUE TITLE
[FEATURE] JupyterLab 3 dynamic extension loading

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10569]
It looks like JupyterLab 3 will offer dynamic extension loading, removing the need for users to run `labextension`. This should be investigated. 

> I am updating #ipyleaflet for #JupyterLab 3, you'll very soon not need to run `labextension build` commands anymore ;)
>
> This will ease the installation process a lot

ref: https://twitter.com/martinRenou/status/1315581075842838528?s=20
ref: https://github.com/jupyterlab/jupyterlab/projects/10

cc @mattpap @philippjfr

**Comment by philippjfr** [comment]
Apparently there is also a script you can run to take care of some of the updates that are required. Will have to look out for that.

**Comment by philippjfr** [comment]
I've now done this for the HoloViz/PyViz extension and while it took a lot of trial and error to package correctly it wasn't too difficult. The recommended approach to distribute it is simply to bundle it into the `PyPI` and `conda` package so I guess we just bundle it inside https://github.com/bokeh/jupyter_bokeh and then ask users to install that.

**Comment by philippjfr** [comment]
Here's my PR for pyviz_comms bundling the JLab 3.0 extension inside the Python package https://github.com/holoviz/pyviz_comms/pull/72

**Comment by Bob-May** [comment]
ValueError: The extension "@bokeh/jupyter_bokeh" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab                        Extension      Package
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.2 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/apputils
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.2 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/rendermime-interfaces
>=6.0.2 <6.1.0                    >=5.0.2 <6.0.0 @jupyterlab/services

For background
 https://github.com/bokeh/jupyter_bokeh/issues/88
https://github.com/bokeh/jupyter_bokeh/issues/92

**Comment by stonebig** [comment]
I confirm I do not need anymore to do "labextension install" on all my usual plugins.
Being nodejs-optional with Jupyterlab-3 is a bit like droping Python2.

**Comment by feynmanliang** [comment]
While we figure out dynamic extension loading, can we please get a dependency version bump? All I did was run the `upgrade_extension` script in https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html and I was able to build / run against Jupyterlab 3. Here's the diff on `package.json`

```
diff --git a/package.json b/package.json
index bbe213f..97f7632 100644
--- a/package.json
+++ b/package.json
@@ -13,41 +13,49 @@
   "license": "BSD-3-Clause",
   "scripts": {
     "build": "tsc && webpack -p",
-    "lint": "eslint -c eslint.json src/**/*.ts",
     "clean": "rimraf dist lib",
+    "lint": "eslint -c eslint.json src/**/*.ts",
     "prepack": "npm run clean && npm run build",
     "watch": "tsc -w --listEmittedFiles"
   },
   "main": "lib/index.js",
   "files": [
-    "{dist,lib}/**/*.{js,js.map,d.ts}"
+    "{dist,lib}/**/*.{js,js.map,d.ts}",
+    "style/index.js"
   ],
   "repository": {
     "type": "git",
     "url": "https://github.com/bokeh/jupyter_bokeh.git"
   },
   "dependencies": {
-    "@jupyterlab/application": "^2.0.2",
-    "@jupyterlab/apputils": "^2.0.2",
-    "@jupyterlab/docregistry": "^2.0.2",
-    "@jupyterlab/notebook": "^2.0.2",
-    "@jupyterlab/rendermime-interfaces": "^2.0.1",
-    "@jupyterlab/services": "^5.0.2",
     "@jupyter-widgets/base": "^3.0.0",
-    "@lumino/coreutils": "^1.3.1",
-    "@lumino/disposable": "^1.3.1",
-    "@lumino/widgets": "^1.9.3"
+    "@jupyterlab/application": "^3.0.4",
+    "@jupyterlab/apputils": "^3.0.3",
+    "@jupyterlab/docregistry": "^3.0.4",
+    "@jupyterlab/notebook": "^3.0.4",
+    "@jupyterlab/rendermime-interfaces": "^3.0.3",
+    "@jupyterlab/services": "^6.0.3",
+    "@lumino/coreutils": "^1.5.3",
+    "@lumino/disposable": "^1.4.3",
+    "@lumino/widgets": "^1.16.1"
   },
   "devDependencies": {
+    "@jupyterlab/builder": "^3.0.0",
+    "@typescript-eslint/eslint-plugin": "^4.8.1",
+    "@typescript-eslint/parser": "^4.8.1",
+    "eslint": "^7.14.0",
+    "eslint-config-prettier": "^6.15.0",
+    "eslint-plugin-prettier": "^3.1.4",
+    "npm-run-all": "^4.1.5",
+    "prettier": "^2.1.1",
     "rimraf": "^3.0.2",
+    "typescript": "~4.1.3",
     "webpack": "^4.42.1",
-    "webpack-cli": "^3.3.11",
-    "typescript": "~3.8.3",
-    "eslint": "^6.8.0",
-    "@typescript-eslint/eslint-plugin": "^2.26.0",
-    "@typescript-eslint/parser": "^2.26.0"
+    "webpack-cli": "^3.3.11"
   },
   "jupyterlab": {
-    "extension": true
-  }
+    "extension": true,
+    "outputDir": "jupyter_bokeh/labextension"
+  },
+  "styleModule": "style/index.js"
 }
```

**Comment by pythonic2020** [comment]
@feynmanliang could you please explain your use of **upgrade_extension** to get jupyter_bokeh to work in JupyterLab 3+.  That web site says that 

`python -m jupyterlab.upgrade_extension .`

should be run "at the root folder of the extension."  Could you please identify what folder that is?  I'm using a conda installation with JupyterLab 3.0.9.

**Comment by feynmanliang** [comment]
You can just apply the diff I posted to `package.json`; the problematic dependencies are the `@jupyterlab/*` ones pinned to `2.0.*`

**Comment by bryevdv** [comment]
cc @mattpap @philippjfr can we release a non-dynamic version as described above?

**Comment by pythonic2020** [comment]
@feynmanliang which package.json?  What is the folder location of that file for you?

**Comment by bryevdv** [comment]
@pythonic2020 The extension repo is here: https://github.com/bokeh/jupyter_bokeh

**Comment by pythonic2020** [comment]
Ok, thank you, but how do I install the edited extension?

**Comment by bryevdv** [comment]
It's in the README there.

**Comment by pythonic2020** [comment]
Thank you.

**Comment by philippjfr** [comment]
>cc @mattpap @philippjfr can we release a non-dynamic version as described above?

That makes a lot of sense in the short term.

**Comment by pythonic2020** [comment]
Why has bokeh blown off updating jupyter_bokeh for so long?  Is there a time frame to get bokeh compatible with JupyterLab 3+?  JupyterLab 3 has had 10 releases already!  As others above have suggested, please get even a simple, temp fix in place, such as a non-dynamic, stop-gap version.

**Comment by bryevdv** [comment]
@pythonic2020 We are all busy and have competing priorities. That kind of comment is really not helpful.

**Comment by ichasepucks** [comment]
@bryevdv would you accept a PR that just bumps the versions in package.json similar to what @feynmanliang suggested?  Or are we looking for the full JL 3 pip install method to be implemented?  I could possibly work on a PR if you're willing to accept it as an interim step?  I'm working on this for our own internal extensions and doing the same.  Let me know what you think.

**Comment by bryevdv** [comment]
@ichasepucks does not actually work. We are going to start from scratch with an empty cookie-cutter project to get re-aligned with current Jupyter best/standard practices. If you can make a quick PR that bumps the package version (and help test it) that would actually be very helpful.

**Comment by bryevdv** [comment]
@ichasepucks @pythonic2020 @feynmanliang @stonebig @Bob-May 

A 3.0.0-dev1 version has been published to both NPM and PyPI (thanks @philippjfr for all the actual work). Please test it and report any observations here. My notes:

* the "loading BokehJS" message does not complete in subsequent loads after a first (but things still function)
* `push_notebook` does not currently work (no comms available)

I would like to merge https://github.com/bokeh/jupyter_bokeh/pull/124 and publish a 3.0.0 version tomorrow (with `push_notebook` as a known issue) assuming some of you can corroborate a 👍

**Comment by philippjfr** [comment]
Hmm, in my local testing push_notebook was working okay using the new extension. Will test that now with the Dev release.

**Comment by bryevdv** [comment]
All note: make sure you do *not* have the alpha/pre-release versions of ipywidgets or jupyterlab-widgets

**Comment by pythonic2020** [comment]
For this new version of jupyter_bokeh, should one install the package from conda/pip, or can one just install the Jlab extension as was the case for Jlab 2?  I'd be happy to test the conda version when it is released...  Many thanks to all involved for all your work!

**Comment by bryevdv** [comment]
@pythonic2020 presently pip install or the previous npm install are available options (though I have not, myself, tested the npm install yet). There will be a conda package at some point as well but maybe not immediately.

**Comment by pythonic2020** [comment]
Using this setup, **push_notebook** still doesn't work for me after using npm install of jupyter_bokeh into a conda environment (Python 3.8.8).  But it is very possible I have screwed up the install somehow.

```
> jupyter labextension list
JupyterLab v3.0.12
C:\Users\me\Miniconda3\envs\forge38\share\jupyter\labextensions
        jupyter-matplotlib v0.8.3 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: C:\Users\me\Miniconda3\envs\forge38\share\jupyter\lab
        @bokeh/jupyter_bokeh v3.0.0-dev1 enabled ok
        jupyterlab-plotly v4.14.3 enabled ok


Uninstalled core extensions:
    @bokeh/jupyter_bokeh
```
```
> conda list jupyterlab_widgets
# packages in environment at C:\Users\me\Miniconda3\envs\forge38:
#
# Name                    Version                   Build  Channel
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge

```
```
> conda list ipywidgets
# packages in environment at C:\Users\me\Miniconda3\envs\forge38:
#
# Name                    Version                   Build  Channel
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
```

Using this code to test:

https://docs.bokeh.org/en/latest/_images/notebook_interactors.png

I don't completely understand this:

```
Uninstalled core extensions:
    @bokeh/jupyter_bokeh
```

Why is jupyter_bokeh listed as a core extension, and how do I get rid of that "uninstalled" message?  Should I uninstall Jlab and start over?  Thanks in advance for any advice.

**Comment by bryevdv** [comment]
I actually can't get the npm install to build
```
jupyter labextension install @bokeh/jupyter_bokeh@3.0.0-dev1
``` 
yields 
<details>
Node v15.12.0

Yarn configuration loaded.
> /Users/bryan/anaconda/envs/230_37/bin/npm pack @bokeh/jupyter_bokeh@3.0.0-dev1
npm notice
npm notice 📦  @bokeh/jupyter_bokeh@3.0.0-dev1
npm notice === Tarball Contents ===
npm notice 1.5kB LICENSE.txt
npm notice 3.5kB README.md
npm notice 25B   lib/extension.d.ts
npm notice 433B  lib/extension.js
npm notice 91B   lib/index.d.ts
npm notice 91B   lib/index.js
npm notice 528B  lib/manager.d.ts
npm notice 471B  lib/manager.js
npm notice 78B   lib/metadata.js
npm notice 585B  lib/plugin.d.ts
npm notice 1.7kB lib/plugin.js
npm notice 1.3kB lib/renderer.d.ts
npm notice 4.5kB lib/renderer.js
npm notice 1.9kB lib/widgets.d.ts
npm notice 7.4kB lib/widgets.js
npm notice 2.8kB package.json
npm notice 0B    style/base.css
npm notice 25B   style/index.css
npm notice === Tarball Details ===
npm notice name:          @bokeh/jupyter_bokeh
npm notice version:       3.0.0-dev1
npm notice filename:      @bokeh/jupyter_bokeh-3.0.0-dev1.tgz
npm notice package size:  8.2 kB
npm notice unpacked size: 26.8 kB
npm notice shasum:        bab96d158a37d6baac37025e58cb5ba8ffd66846
npm notice integrity:     sha512-EKIUnJRlXK+h5[...]KmRU7rjJlSyew==
npm notice total files:   18
npm notice
bokeh-jupyter_bokeh-3.0.0-dev1.tgz

Node v15.12.0

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /Users/bryan/anaconda/envs/230_37/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.40s.

> node /Users/bryan/anaconda/envs/230_37/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.44s.

> node /Users/bryan/anaconda/envs/230_37/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@bokeh/jupyter_bokeh/style/index.js' in '/Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/build'
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1668:28
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:712:13
    at eval (eval at create (/Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:628:24
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:782:8
    at /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:902:5
resolve '@bokeh/jupyter_bokeh/style/index.js' in '/Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/build'
  Parsed request is a module
  using description file: /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/build/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/build/node_modules doesn't exist or is not a directory
      looking for modules in /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules
        existing directory /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh
          using description file: /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh/package.json (relative path: .)
            using description file: /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh/package.json (relative path: ./style/index.js)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh/style/index.js doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh/style/index.js.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh/style/index.js.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh/style/index.js.wasm doesn't exist
              as directory
                /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/staging/node_modules/@bokeh/jupyter_bokeh/style/index.js doesn't exist
      /Users/bryan/anaconda/envs/230_37/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /Users/bryan/anaconda/envs/230_37/share/jupyter/node_modules doesn't exist or is not a directory
      /Users/bryan/anaconda/envs/230_37/share/node_modules doesn't exist or is not a directory
      /Users/bryan/anaconda/envs/230_37/node_modules doesn't exist or is not a directory
      /Users/bryan/anaconda/envs/node_modules doesn't exist or is not a directory
      /Users/bryan/anaconda/node_modules doesn't exist or is not a directory
      /Users/bryan/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/Users/bryan/anaconda/envs/230_37/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/bryan/anaconda/envs/230_37/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 134, in start
    production = production, minimize = self.minimize, app_options=app_options)

  File "/Users/bryan/anaconda/envs/230_37/lib/python3.7/site-packages/jupyterlab/commands.py", line 470, in build
    production=production, minimize=minimize, clean_staging=clean_staging)

  File "/Users/bryan/anaconda/envs/230_37/lib/python3.7/site-packages/jupyterlab/commands.py", line 678, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: lab
</details>

To  be completely honest I would be 100% OK with just making pip/conda installs of the pre-built extension being the only supported mechanism. cc @mattpap @philippjfr

**Comment by bryevdv** [comment]
FYI I've also published `3.0.0-dev2` with @philippjfr  fix for classic notebook

**Comment by pythonic2020** [comment]
**push_notebook** still doesn't work for me using `3.0.0-dev2` with configuration listed above.  **push_notebook** has always worked for me in classic notebook.

**Comment by philippjfr** [comment]
Can you try the following?

```
pip uninstall jupyter_bokeh
jupyter labextension uninstall @bokeh/jupyter_bokeh
pip install --pre jupyter_bokeh
```

**Comment by pythonic2020** [comment]
I am a conda user, no pip installs related to bokeh or jupyter.  jupyter_bokeh isn't installed via conda, either.  Just the labextension is installed.  Is there a way I can install the dev version via conda?

**Comment by philippjfr** [comment]
We'll publish the package on conda eventually, but for now just install it using pip into your conda env for testing.

**Comment by pythonic2020** [comment]
Will do.

**Comment by pythonic2020** [comment]
**push_notebook** works perfectly in Jlab 3! Yahoo!  Great job, everyone!

```
> pip install --pre jupyter_bokeh
Collecting jupyter_bokeh
  Downloading jupyter_bokeh-3.0.0.dev2-py3-none-any.whl (1.4 MB)
...
Installing collected packages: jupyter-bokeh
Successfully installed jupyter-bokeh-3.0.0.dev2
(forge38) PS C:\Users\bwroc> jupyter labextension list
JupyterLab v3.0.12
C:\Users\me\Miniconda3\envs\forge38\share\jupyter\labextensions
        jupyter-matplotlib v0.8.3 enabled ok
        @bokeh/jupyter_bokeh v3.0.0-dev2 enabled ok (python, jupyter_bokeh)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: C:\Users\me\Miniconda3\envs\forge38\share\jupyter\lab
        jupyterlab-plotly v4.14.3 enabled ok


Uninstalled core extensions:
    @bokeh/jupyter_bokeh
```
![Jlab3_jup-bokeh](https://user-images.githubusercontent.com/61034042/112000317-7defaa00-8ae3-11eb-9a54-488b6742423a.png)

**Comment by bryevdv** [comment]
pip package for 3.0 is published. Conda package should be available in the next few days. It is still TBD if we will support NPM installs going forward. 

In any case, I will go ahead and close this (follow on issues are all in the [`bokeh/jupyter_bokeh` issue tracker](https://github.com/bokeh/jupyter_bokeh/issues)
