### ISSUE TITLE
Custom extension breaks with id as key in a dict param

### ISSUE THREAD

**Issue by govinda18** [bokeh/bokeh#11694]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh==2.3.3, panel==0.12.1

#### Description of expected behavior and the observed behavior
I am trying to build a bokeh extension for [panel](https://panel.holoviz.org/). I am facing a weird error. When I try to pass an id key to a dict param, it throws a weird error. Check the stacktrace below.

#### Complete, minimal, self-contained example code that reproduces the issue
It would be tough to show a complete reproducer. I can demonstrate it using a library called panel_highcharts.
```
import panel as pn
import panel_highcharts as ph
pn.extension('highchart')

c1 = ph.HighChart(object={
    'series': [{
        'data': [1, 2, 3, 4, 5]
    }],
    'yAxis': {
        'id': 'asd'
    }
})

c1
```

Note that this is not an error in panel_highcharts as I was able to produce it in a completely different project as well. Simply removing the id key or changing to something else works.

#### Stack traceback and/or browser JavaScript console output
```
VM326 bokeh-2.3.3.min.js:165 Uncaught Error: reference {"id":"asd"} isn't known (not in Document?)
    at n (VM326 bokeh-2.3.3.min.js:165)
    at VM326 bokeh-2.3.3.min.js:165
    at n (VM326 bokeh-2.3.3.min.js:165)
    at VM326 bokeh-2.3.3.min.js:165
    at n (VM326 bokeh-2.3.3.min.js:165)
    at Function._resolve_refs (VM326 bokeh-2.3.3.min.js:165)
    at Function._initialize_references_json (VM326 bokeh-2.3.3.min.js:165)
    at Function.from_json (VM326 bokeh-2.3.3.min.js:165)
    at Object.t.embed_items_notebook (VM326 bokeh-2.3.3.min.js:589)
    at embed_document (<anonymous>:5:22)
```

**Comment by philippjfr** [comment]
Seems like an issue with the way Bokeh resolves Model references. It seems reasonably common to want to serialize an object with an `id` attribute so imo Bokeh's serialization should have some other sentinel value that declares something as a Model reference.

**Comment by bryevdv** [comment]
First things first: please try to reproduce with the latest release (2.4) in case the issue was already fixed at some point.

**Comment by govinda18** [comment]
The error persists with version 2.4 as well.

I would expect so as well because it seems [this code](https://github.com/bokeh/bokeh/blob/branch-3.0/bokehjs/src/lib/document/document.ts#L375) was not change in a while.

I can understand now why am able to get around with passing some other key along with id as [this code](https://github.com/bokeh/bokeh/blob/3492419aaf6298a1fa5dd330d2b04932c36ee091/bokehjs/src/lib/core/util/refs.ts#L23) seems to specifically check for that. The thing is based on id I would want to do some modifications on the js layer, so I would prefer passing id as a single key.

**Comment by mattpap** [comment]
We will need a better way of encoding references. This will be resolved as a part of upcoming serialization/protocol improvements.

**Comment by mattpap** [comment]
Or actually dictionaries, which is the main part of that work.
