### ISSUE TITLE
fill_color argument doesn't handle RGB(A) tuples properly

### ISSUE THREAD

**Issue by tyarkoni** [bokeh/bokeh#1381]
The documentation says that the fill_color and line_color arguments to most plotting methods in bokeh.plotting can be a tuple of RGB or RGBA values, but this doesn't seem to work. When a single tuple is passed, the problem is that _match_data_params() doesn't check for tuples, but only for strings or hex codes. This could be trivially fixed by adding an isinstance(val, tuple) check in https://github.com/tyarkoni/bokeh/blob/cbaec4fef462a5d539d0fdadaf6c31cc5fb98765/bokeh/plotting_helpers.py#L111. I can submit a PR if desired.

When passing an iterable, things are more complicated. I'm not sure I understand what's going on 100%, but I think the problem is that the input iterable gets bound to a data field, which means it gets treated as a DataSpec rather than ColorSpec instance. After that, there's no way to call _formattuple to retrieve the correct color. Not sure how you want to handle this, but it would seem reasonable to either (a) do the tuple formatting/conversion within _match_data_params(), after which it's fine to treat bind the values directly to the datasource, or (b) to add some additional logic within the iterable-specific blocks that makes sure the color-related fields get treated as ColorSpecs.

**Comment by colinfang** [comment]
This issue still exists! I think we should simply change the documents saying that we don't support tuple.

**Comment by birdsarah** [comment]
That's ok - we can re-open. This closing should have had the note "Discussion is now more than 3 months old. Can re-open if renewed interest." - my apologies for not putting this comment in.

**Comment by tyarkoni** [comment]
Not sure whether the underlying issue is worth discussing or fixing, but I agree with @colinfang that the docs should probably be changed to ensure consistency with the current codebase.

**Comment by bryevdv** [comment]
OK we need some concrete code examples to clarify this. With 0.9.1, the following code sample:
```
from bokeh.plotting import *
output_file("foo.html")
p = figure()
p.circle([1,2,3], [4,5,6], size=50, fill_color=(128, 200, 255, 0.1))
p.square([1,2,3], [7,8,9], size=50, fill_color=(250, 200, 100))
```
Yields this result:
<img width="598" alt="screen shot 2015-07-11 at 2 25 44 am" src="https://cloud.githubusercontent.com/assets/1078448/8632890/2b8fda7e-2774-11e5-8925-0b8dc47fdbb4.png">
which I would judge to be correct. Can anyone provide a concrete example of code with a screenshot that illustrates broken behavior?

**Comment by bryevdv** [comment]
Probably relevant: https://github.com/bokeh/bokeh/commit/da51858778d1f78dc2007d54877ec1980b0af08d 

commit was two weeks ago, went in 0.9.1

**Comment by colinfang** [comment]
@bryevdv sorry, my mistake, I tested in some dev 0.9.0+ version. I agree it is fixed in 0.9.1

**Comment by tyarkoni** [comment]
Looks good to me; closing!

**Comment by jmhessel** [comment]
Sorry to bump this, but I think this might still be broken.

If you're trying to use a list of tuples (so each circle can have a different color) it's still broken.

**Comment by damianavila** [comment]
Probably a new issue is OK, and include the example with the breaking stuff... thanks!
