### ISSUE TITLE
Using vform method to generate layout can cause extra components to be in the document root

### ISSUE THREAD

**Issue by clairetang6** [bokeh/bokeh#3943]
I was trying to add widgets to a page layout using vform, but found a bug that was causing extra plot elements to be displayed on the screen. This was only happening when one of the children passed to vform was another layout created by hplot, vplot, or gridplot. After some digging, I found that the children passed to vform aren't removed from the document root like the children passed to hplot, vplot, or gridplot. I fixed this bug, added some tests, and will be submitting a pull request. 

Example code to reproduce bug:
```
from bokeh.models import Button
from bokeh.plotting import figure, gridplot
from bokeh.io import vform, output_file, show

output_file("text.html")

w = 300
h = 150

fig1 = figure(width=w, height=h, tools=[])
fig1.circle(x=[0,1,3,4], y=[10,4,1,5])

fig2 = figure(width=w, height=h, tools=[])
fig2.circle(x=[0,1,3,4], y=[10,4,1,5])

fig3 = figure(width=w, height=h, tools=[])
fig3.circle(x=[0,1,3,4], y=[10,4,1,5])

fig4 = figure(width=w, height=h, tools=[])
fig4.circle(x=[0,1,3,4], y=[10,4,1,5])

grid = gridplot([[fig1, fig2], [fig3, fig4]])
button = Button(label="Click")

v = vform(button, grid)
show(v)
```

![image](https://cloud.githubusercontent.com/assets/4241244/13339036/7d2bc7c4-dbda-11e5-881e-78e428802235.png)

**Comment by birdsarah** [comment]
Hi @clairetang6, thanks for the report, I can't reproduce with bokeh-0.12.0dev1.

See: http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/3943%20vform.ipynb

Can you clarify which version of bokeh you're finding this error with.

**Comment by clairetang6** [comment]
Hi, the version is '0.12.0dev1-98-g7f81413-dirty'. 

I think this has something to do with the show() working as expected by only displaying the objects that are passed to it, but I'm pretty sure the bug is still there. I also don't see the extra plots in a Jupyter notebook, but try printing out v.document.roots after running that code block. I think there will be two components in there, both the GridPlot and the VBoxForm. With the fix, only the VBoxForm is in the document root. Maybe try running the code using the bokeh command line tools too? It seems like when show is bypassed by bokeh serve, bokeh html, and bokeh json, then the extra plots are there. 

Something else I just noticed was that running my example code block twice results in more components in the document root. That might also lead to bugs when saving files from the Jupyter notebook, but I haven't looked into this.

**Comment by clairetang6** [comment]
@birdsarah I spent a little more time to try and figure this out. The bug can be seen when using the bokeh command line tools because those tools go through the document root to find the components to render. But when the output is set to the notebook, and interestingly also when the output is set to an html file using output_file('test.html'), and then displayed in the notebook (or saved to html and opened in a new tab) using show, the components to render are found from the object passed to show(obj) and not the document. 

For example, in bokeh/command/subcommands/html.py, the first parameter passed is **doc**, 

Line 91:
```python
 return standalone_html_page_for_models(doc, resources=resources, title=None)
```

while in bokeh/io.py in the save function, which is called when the output is a file, the first parameter is **obj**
Line 415:
```python
 html = standalone_html_page_for_models(obj, resources, title)
```

Because of this, the bug is hidden when using output_notebook or output_file, but appears when using bokeh serve, bokeh html, and bokeh json. 

I have not tried using the server from the notebook, but from the code it seems like it would also result in the duplicate plots being shown since it uses the document in its "push to server" method. 

I still think vform not removing its children is a bug. Although it doesn't show up in some situations, it causes the wrong output when used with bokeh serve, which is probably the way vform is used the most. Also, vform should remove its children from the document root because it is the expected behavior that gridplot, hplot, and vplot already do. 

Thanks for looking at this with me. 

P.S. 
The `standalone_html_page_for_models` ends up calling `_standalone_docs_json_and_render_items([with either doc or obj])`. This is also the function that gets called for the notebook output, and like the html file output also uses the object passed to show(obj).

**Comment by birdsarah** [comment]
Dirty means that you've got changes on your local git repo. It's definitely worth checking on a clean version.

Can you be more specific about "using the command line tools",  when making the notebook, I also did a standalone version and ran `python 3943.py` you can see the output here: https://rawgit.com/birdsarah/bokeh-miscellany/master/3943.html

cc: @bryevdv @havocp who have lots of insight on the document and its roots.

I'm not saying you don't have a bug, i just haven't been able to reproduce, what you're describing, which is why this is still in discussion mode.

**Comment by clairetang6** [comment]
Thanks, I have checked out the clean version of the repo. When I say command line tools, I just mean bokeh serve, bokeh html, and bokeh json. 

So I took the code that I posted in the first message and put it in a file called app.py. I also added two lines at the bottom, `import bokeh, print(bokeh.__version__)`. Then when I run this file using bokeh serve, this is the output that I get. 

```
(bokeh-dev)ClairesMacBook:test claire$ BOKEH_SIMPLE_IDS=true /users/claire/documents/bokeh/bin/bokeh serve --show app.py
2016-02-25 21:49:18,906 Starting Bokeh server version 0.12.0dev1-96-gcf82e80
2016-02-25 21:49:18,906 Allowed Host headers: ['localhost:5006']
2016-02-25 21:49:18,906 These host origins can connect to the websocket: ['localhost:5006']
2016-02-25 21:49:18,907 Patterns are: [('/app/?', <class 'bokeh.server.views.doc_handler.DocHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x1058a5850>, 'bokeh_websocket_path': '/app/ws'}), ('/app/ws', <class 'bokeh.server.views.ws.WSHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x1058a5850>, 'bokeh_websocket_path': '/app/ws'}), ('/app/autoload.js', <class 'bokeh.server.views.autoload_js_handler.AutoloadJsHandler'>, {'application_context': <bokeh.server.application_context.ApplicationContext object at 0x1058a5850>, 'bokeh_websocket_path': '/app/ws'}), ('/static/(.*)', <class 'bokeh.server.views.static_handler.StaticHandler'>)]
2016-02-25 21:49:18,913 Starting Bokeh server on port 5006 with applications at paths ['/app']
2016-02-25 21:49:19,554 /Users/claire/Documents/test/app.py: call to output_file() ignored when running scripts with the 'bokeh' command.
2016-02-25 21:49:19,581 /Users/claire/Documents/test/app.py: call to show() ignored when running scripts with the 'bokeh' command.
0.12.0dev1-96-gcf82e80
2016-02-25 21:49:19,596 W-1004 (BOTH_CHILD_AND_ROOT): Models should not be a document root if they are in a layout box: GridPlot, ViewModel:GridPlot, ref _id: 1073
2016-02-25 21:49:19,603 200 GET /app (::1) 63.94ms
2016-02-25 21:49:20,111 WebSocket connection opened
2016-02-25 21:49:20,111 Receiver created for Protocol(u'1.0')
2016-02-25 21:49:20,112 ServerHandler created for Protocol(u'1.0')
2016-02-25 21:49:20,112 ServerConnection created
2016-02-25 21:49:20,250 Sending pull-doc-reply from session '0han8dE6amBo1Nqh8AnSzl9mldLV1POZwV8JQUheQJlt'
2016-02-25 21:49:33,919 [pid 70365] 1 clients connected
2016-02-25 21:49:33,919 [pid 70365]   /app has 1 sessions with 0 unused
```

And the tab that opens looks like this 
![image](https://cloud.githubusercontent.com/assets/4241244/13344375/3dd89068-dc0a-11e5-8fd1-d36b0a638af0.png)

When I try using bokeh html, I get the same result. 

```
(bokeh-dev)ClairesMacBook:test claire$ BOKEH_SIMPLE_IDS=true /users/claire/documents/bokeh/bin/bokeh html app.py
0.12.0dev1-96-gcf82e80
ERROR:/Users/claire/Documents/bokeh/bokeh/core/validation/check.pyc:W-1004 (BOTH_CHILD_AND_ROOT): Models should not be a document root if they are in a layout box: GridPlot, ViewModel:GridPlot, ref _id: 1073
(bokeh-dev)ClairesMacBook:test claire$ http-server
Starting up http-server, serving ./
Available on:
  http:127.0.0.1:8080
  http:10.0.0.5:8080
```

![image](https://cloud.githubusercontent.com/assets/4241244/13344448/dba4b420-dc0a-11e5-8269-7b574ff48bb4.png)

And when I run bokeh json, I can pretty-print the json and see that there are two ids in the root.

![image](https://cloud.githubusercontent.com/assets/4241244/13344529/9b431772-dc0b-11e5-85db-9b9d09ddc6db.png)

**Comment by clairetang6** [comment]
@birdsarah I also just tried python app.py, and the bug does not appear, so maybe running this way also is producing html using output_file() and show(). 

```
(bokeh-dev)ClairesMacBook:test claire$ python app.py
0.12.0dev1-96-gcf82e80
```

![image](https://cloud.githubusercontent.com/assets/4241244/13344583/32f75574-dc0c-11e5-81b7-185e25e05935.png)

**Comment by bryevdv** [comment]
Hi @clairetang6 thanks for all the detailed investigation. I think this is also related to #3671 and is definitely something we need to make better. I have some ideas that could hopefully preserve the "ease of use" in simple situations, without causing the problems you are seeing here. I'm currently on a short vacation, can we plan to discuss this next week?

**Comment by clairetang6** [comment]
Hi @bryevdv, yes, I think the issue that you linked is related. Something to add to the discussion there might be how everything would work using the bokeh server, which I think might be using the global document? As a first-time user, it was a little bit confusing figuring out the best way to do what I wanted, but I really appreciate your guys' effort to provide the multiple levels of interfaces. Of course we can discuss anytime. Thank you and @birdsarah for your quick responses. It's been fun using bokeh, and I've already found good use for it (love the lasso tool) in my own work.

**Comment by patrickgalliani** [comment]
Placing this here because I thought it might be helpful for this discussion.  I seemed to have found a similar problem.  Linked here: 

https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/uyUyERNaoUE

**Comment by clairetang6** [comment]
Fixed by [#3944](https://github.com/bokeh/bokeh/pull/3944)

**Comment by jbrambleDC** [comment]
I am assuming this fix wont hit production until 0.12 release. I am working with a 0.11, and this is still an issue. it seems that switching to Figure instead of figure, is a fix.

**Comment by koganm** [comment]
Calling curdoc().clear(), as suggested in https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/uyUyERNaoUE, ended up doing the trick for me
