### ISSUE TITLE
DataTable header height not large enough to fit header text - in Jupyter Notebook

### ISSUE THREAD

**Issue by sanga** [bokeh/bokeh#4680]
Code to repro (note: running in jupyter notebook):

```
df = pd.DataFrame({'a': range(5), 'b': range(5)})
columns = [TableColumn(field=k, title=k) for k in df.columns]
source = ColumnDataSource(df)
data_table = DataTable(source=source,columns=columns, fit_columns=True, row_headers=False, height=400)

show(widgetbox(data_table));
```

<img width="487" alt="screen shot 2016-06-26 at 13 21 25" src="https://cloud.githubusercontent.com/assets/2088/16361683/d484dfee-3ba0-11e6-8cdc-3d5b7368a492.png">

```
Python version      :  3.5.1 (default, Dec 26 2015, 18:11:22)
IPython version     :  4.2.0
Bokeh version       :  0.12.0rc4
BokehJS static path :  /usr/local/lib/python3.5/site-packages/bokeh/server/static
```

Observed on most recent Firefox and Chrome.

**Comment by sanga** [comment]
slick-grid appears to be dead btw. Perhaps updating to an actively maintained fork might fix the problem?

i.e.

https://github.com/6pac/SlickGrid

**Comment by sanga** [comment]
Note this is actually the case in your docs too

http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#data-table

**Comment by sanga** [comment]
Interestingly this works correctly in the "export_csv" server app - both when I run it locally and for example here:

https://demo.bokehplots.com/apps/export_csv

**Comment by sophiajiyoung** [comment]
I get the same issue! (Previous version works fine.) Is there a workaround for this?

**Comment by muyiwaolu** [comment]
I'm having the same issue. The columns aren't aligning and the font is too big for the headers.

**Comment by bryevdv** [comment]
ping @birdsarah can you take a quick look when you have a chance? Maybe this is a quick fix

**Comment by birdsarah** [comment]
will do

**Comment by compeanansi** [comment]
I'm still having this issue

**Comment by birdsarah** [comment]
Having looked quickly, this does not appear to be a quick fix.

**Comment by sanga** [comment]
How about upgrading the underlying js lib btw? Would you like me to create a separate issue for that? 

(as a reminder/snipped from earlier in this thread):

"slick-grid appears to be dead btw. Perhaps updating to an actively maintained fork might fix the problem?

i.e.

https://github.com/6pac/SlickGrid"

**Comment by birdsarah** [comment]
from @troianow

When running the first half of the bokeh/examples/glyphs/data_tables.py example, i.e.up to 
`data_table = DataTable(source=source, columns=columns, editable=True)`
and plot with:
`plotting.show(data_table)`
the result has misligned column headers:
![image](https://cloud.githubusercontent.com/assets/1373343/9260220/70f80454-41d4-11e5-84ea-cfac980fc5bb.png)

If, on the other hand, I use:
`plotting.show(vplot(data_table))`
It displays the table correctly: 
![image](https://cloud.githubusercontent.com/assets/1373343/9260261/b007f8de-41d4-11e5-8db6-bc67b51fc972.png)

It behaves that way on firefox 40 and chrome 44 on Windows 7.

**Comment by compeanansi** [comment]
Adding a call to vplot() didn't fix my issue instead I got a deprecation warning. Switching to Column() as requested didn't work either.

![screen shot 2016-09-09 at 1 06 44 pm](https://cloud.githubusercontent.com/assets/6817460/18395829/70cfe9fc-768e-11e6-8e7a-9c1644acc5a1.png)

**Comment by birdsarah** [comment]
@compeanansi - that message regarding vplot was from 2015. Sorry for the misdirection - I copied it here for completeness from another issue.

**Comment by esvhd** [comment]
+1, having the same issue here, think I got this after upgrading to 0.12. Would be great to see a fix here.

Platform:
Max OS El Capitan
Safari version 9.1.3
Chrome version 52.0.2743.116

Thank you.

**Comment by ijstokes** [comment]
I'm suffering from this as well.  What's that fancy `vplot` trick @birdsarah suggested above may be a workaround?  Where does `vplot()` come from?  Is Bokeh using `qgrid` https://github.com/quantopian/qgrid to make the data table happen?

**Comment by bryevdv** [comment]
@ijstokes the built in data table is implemented using SlickGrid. Don't use `vplot` it was deprecated some time ago.

**Comment by esvhd** [comment]
I think vplot() has be deprecated in newer versions of bokeh though.

**Comment by mrksr** [comment]
I have the same issue on current Chrome and Bokeh version `0.12.2`:
![bokeh_table](https://cloud.githubusercontent.com/assets/5184063/19734265/3323eba6-9ba7-11e6-8286-9579d82375a3.PNG)

Given that `vplot` is deprecated, is there another workaround?

**Comment by mattpap** [comment]
Given the visual appearance of this bug and IPython version number, I would say this issue is similar to #5398, i.e. IPython uses bootstrap which changes box model for all HTML tags, which in particular interferes visibly with SlickGrid.

**Comment by gryBox** [comment]
@mrksr this issue was fixed for us in 12.3

**Comment by gz** [comment]
Not fixed for me with 0.12.3 and Chrome 53. Looks still like the picture @mrksr posted.

**Comment by bryevdv** [comment]
@sanga @gz @gryBox @esvhd @ijstokes @birdsarah is it possible for (at least) one of you to try out building and running with #5421 to confirm that it fixes things for you? remember you can set `BOKEH_RESOURCES=inline` to for using locally build BokehJS, and full info is in the dev guide: http://bokeh.pydata.org/en/latest/docs/dev_guide.html

**Comment by philippjfr** [comment]
I can confirm with the PR tables now render correctly:

<img width="408" alt="screen shot 2016-11-01 at 4 29 02 pm" src="https://cloud.githubusercontent.com/assets/1550771/19897592/78142a70-a050-11e6-973c-a51ddec326a5.png">

**Comment by bryevdv** [comment]
Great, I will merge now!
