### ISSUE TITLE
Version mismatch bug in 0.12.1

### ISSUE THREAD

**Issue by dmho418** [bokeh/bokeh#4957]
**https://cdn.pydata.org/bokeh/release/bokeh-0.12.1.min.js** triggers the messages:
```
bokeh-0.12.1.min.js:67 Bokeh: JS/Python version mismatch
bokeh-0.12.1.min.js:67 Bokeh: Library versions: JS (0.12.0)  /  Python (0.12.1)
```

**Comment by mattpap** [comment]
This was fixed in #4898.

**Comment by cenveoanalyst** [comment]
I recently installed 0.12.1 and it's still showing this error.

**Comment by bryevdv** [comment]
Yes the bug was fixed after 0.12.1 it is working correctly in recent dev builds.

**Comment by cenveoanalyst** [comment]
so I need to be using a dev build instead of the one distributed via pip?

**Comment by bryevdv** [comment]
The error message is harmless. The versions match correctly it's the warning that is incorrect.

**Comment by mariagitgit** [comment]
I am trying to embed a Bokeh plot in a simple web page, using your inline embedding functionality together jQuery. This error message is coming up and the Bokeh plot is not being displayed. I have posted a question on stack overflow, if you could please have a look: http://stackoverflow.com/questions/39173697/bokeh-inline-embedding-failed-to-load-resource

Admittedly, I am very new to programming, so I might be doing something very wrong. I have, however, on previous occasions successfully embedded Bokeh plots inline before. It is only now, when I use Bokeh together with jQuery, that the issue arises.

**Comment by bryevdv** [comment]
Hi @mariagitgit we reserve the issue tracker for bug reports and feature requests, the appropriate place for general support questions is the mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh
