### ISSUE TITLE
WebSocket connection closed: code=None, reason=None

### ISSUE THREAD

**Issue by moshiour** [bokeh/bokeh#6463]
Hi,

I have experienced with "WebSocket connection closed" to run bokeh apps with following commands

moshiour$ bokeh serve --show Ms-app

2017-06-13 15:51:55,490 Starting Bokeh server version 0.12.5

2017-06-13 15:51:55,497 Starting Bokeh server on port 5006 with applications at paths ['/Ms-app']

2017-06-13 15:51:55,498 Starting Bokeh server with process id: 3875

0:44: execution error: "http://localhost:5006/Ms-app" doesn’t understand the “open location” message. (-1708)

69:77: execution error: Can’t get application "chrome". (-1728)

70:78: execution error: Can’t get application "firefox". (-1728)

2017-06-13 15:52:09,355 200 GET /Ms-app (::1) 12722.31ms

2017-06-13 15:52:09,624 101 GET /Ms-app/ws?bokeh-protocol-version=1.0&bokeh-session-id=fKo2rCl0r12HkMTHRZXRZ1op3qPTXigdLwMrxF1uOC3b (::1) 1.31ms

2017-06-13 15:52:09,624 WebSocket connection opened

2017-06-13 15:52:09,627 ServerConnection created

2017-06-13 15:52:10,159 WebSocket connection closed: code=None, reason=None

Any help would be appreciated.

Thanks in advance!

# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

**Comment by bryevdv** [comment]
Please provide all the information asked for. Additionally what version of Tornado do you have installed?

**Comment by moshiour** [comment]
Hi,
Sorry for short question. Here is my details:
OS: OSX: Sierra 10.12.5
Browser: Safari 10.1.1
Anaconda  4.4
Python  3.6 
Bokeh   0.12.5 
tornado    4.5.1
====================

Thanks again
Moshiour

**Comment by bryevdv** [comment]
dupe of https://github.com/bokeh/bokeh/issues/6152

Tornado 4.5 introduced a breaking incompatibility with Bokeh. This has been resolved in master, recent dev builds and release candidates, and in `0.12.6` (just now released)

**Comment by Allenite** [comment]
I'm still seeing this message when I try to plot a large polyline shapefile.  I get this when using Google Maps tiles or with no tiles.  The map displays, then this message pops up in the console whenever I try to select a tool from the toolbox.

Hi,
Sorry for short question. Here is my details:
OS: Windows 10 Pro
Browser: Chrome 66.0.3359.139
Anaconda 4.5.1
Python 3.6.5
Bokeh 0.12.15
tornado 5.0.2

Happy to provide the code if that would help.

**Comment by bryevdv** [comment]
We can try to look into it at some point, but be aware that most browsers have their own arbitrary max websocket message size, that we have no control over. From your description of a "large" shapefile, my guess is that this is what you are running into, and not the tornado version issue at all. In which case, there is not really anything we can suggest except to find a way to break your data up into multiple CDS's.

**Comment by Allenite** [comment]
Got it, thanks Bryan.  I've been thinking of filtering the CDS based on the zoom level and window extents - would that make a difference on a mapping application.  Before I do, I wanted to ask if Bokeh does some of that by default (meaning any additional efforts on my end may not yield much of a performance benefit)?
