### ISSUE TITLE
Bokeh rendering glyphs in inactive tabs

### ISSUE THREAD

**Issue by Charles75382** [bokeh/bokeh#7438]
After a lot of frustration, I finally found a solution to my performance issues with Bokeh in my server web app. I was having tremendous slowdowns that only increased when I added hovertools with custom tooltips to each of the plots I had under a tab.

I was able to return the performance to a very good state by having a JS Callback in the tab widget set the .visible property of all GlyphRenderers to false if they weren't behind the active tab. This is something that the widget should be doing by default IMO.

**Comment by bryevdv** [comment]
Seems reasonable in principle, tho there are certainly caveats. Plots in tabs need to record and respond to data updates, e.g. so that whenever they do become visible they are properly up to date. Maybe it would be possible to have a setting that could cause `render` to return immediately without drawing, which `Tabs` could coordinate on its children. 

cc @bokeh/dev

**Comment by Charles75382** [comment]
What kind of updates? Haven't tried streaming data but I share a y-range across all graphs and when one range is changed in one tab, when selecting another tab the graph is redrawn to the correct (previous graph's) range. Seems as long as the data structures are set up in an object oriented way when the graph is redrawn it should have access to the current state.

**Comment by jukiewiczm** [comment]
@Charles75382 
Would you mind sharing the callback you implemented? You already provided some guidance about what needs to be done but as I'm pretty bad at javascript I could use a bit more.

**Comment by SeanCGriffin** [comment]
Have there been any updates to this? I have tried doing something similar (I have a lot of tabs with several plots all being streamed to in real time) and I think that this would be a good solution to helping with massive lag. Unfortunately, when trying the CustomJS solution above, all the contents of all tabs disappear.

**Comment by bryevdv** [comment]
@SeanCGriffin There is never any reason to ask this on an OSS tracker. If there were updates, they would be recorded here in the issue. No one has done any work on this that I am aware of. (There are limited resources, and very many competing priorities)

**Comment by jukiewiczm** [comment]
@SeanCGriffin 
Check out the javascript snippet that I posted it seems to do the job pretty well. It does for me at least

**Comment by SeanCGriffin** [comment]
@jukiewiczm 
I did; unfortunately the JS leaves me with a bunch of empty / broken tabs. I believe something similar to the JS is the solution, but I need to figure out why when I click away from the active tab everything collapses and there are no figures/anything shown anymore.

**Comment by jbednar** [comment]
> There is never any reason to ask this on an OSS tracker. If there were updates, they would be recorded here in the issue.

I guess that's true of Bokeh, under your excellent stewardship, but there are definitely many cases in the OSS projects I run where we've fixed things or moved in a different direction and didn't realize or remember about an issue about it.  We find things like that whenever we triage open issues.

In any case, Panel (based on Bokeh) now allows dynamically populating tabs to avoid this issue; see https://github.com/holoviz/panel/pull/991.

**Comment by bryevdv** [comment]
@mattpap given your comments in the latest blog, is this still an issue? Or were those near-term speculative based on the new layout work?

**Comment by mattpap** [comment]
Recent changes may help to some extent, as changes to one tab don't require rerendering of all tabs. However, on functional level, this problem still persists and needs to be fixed in plots rather than tabs.
