### ISSUE TITLE
RuntimeError('Cannot apply patch to [id] which is not in the document',) when clicking the Reset button

### ISSUE THREAD

**Issue by aliddell** [bokeh/bokeh#7738]
When I add a figure to a layout after the layout is created, then pan it and reset it, I get the following error (or similar) in the console:

```
2018-04-03 13:39:59,227 error handling message Message 'PATCH-DOC' (revision 1): RuntimeError('Cannot apply patch to E0EFBC2CAC454F319C97899A5E36FB03 which is not in the document',)
2018-04-03 13:39:59,229 error handling message Message 'PATCH-DOC' (revision 1): RuntimeError('Cannot apply patch to E0EFBC2CAC454F319C97899A5E36FB03 which is not in the document',)
2018-04-03 13:39:59,231 error handling message Message 'PATCH-DOC' (revision 1): RuntimeError('Cannot apply patch to E0EFBC2CAC454F319C97899A5E36FB03 which is not in the document',)
```

This does *not* occur if the figure is added to the column on creation (see `tan(x)` example below).

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Windows 10, Python 3.6.4, Bokeh 0.12.15, NumPy 1.14.0, Chrome 65.0.3325.181 (also occurs on Brave 0.22.13).

#### Description of expected behavior and the observed behavior

Expected behavior: no errors thrown in either the JS console or the terminal.

Observed behavior: figure resets, but errors are thrown.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import numpy as np

from bokeh.layouts import column, layout
from bokeh.models import Button
from bokeh.plotting import figure, curdoc

def plot_sin():
	global left_col
	
	if len(left_col.children) == 1:
		p = figure(plot_width=500, plot_height=300)
		x = np.linspace(0, 1, 100)
		p.circle(x, np.sin(2*np.pi*x), color="red")

		left_col.children.append(p)
	
def plot_cos():
	global right_col
	
	if len(right_col.children) == 1:
		p = figure(plot_width=500, plot_height=300)
		x = np.linspace(0, 1, 100)
		p.circle(x, np.cos(2*np.pi*x), color="red")
		
		right_col.children.append(p)
	
doc = curdoc()

sin_button = Button(label="plot sin(x)", width=100, button_type="danger")
sin_button.on_click(plot_sin)

tan_button = Button(label="plot tan(x)", width=100, button_type="success")

cos_button = Button(label="plot cos(x)", width=100, button_type="danger")
cos_button.on_click(plot_cos)

tan_figure = figure(plot_width=500, plot_height=300)
x = np.linspace(0, 1, 100)
tan_figure.circle(x, np.tan(2*np.pi*x), color="green")

left_col = column([sin_button], name="left", width=500)
mid_col = column([tan_button, tan_figure], name="middle", width=500)
right_col = column([cos_button], name="right", width=500)

page = layout(children=[[left_col, mid_col, right_col]])
doc.add_root(page)
```

#### Stack traceback and/or browser JavaScript console output

Here's the JS console output:
```
session.js:85 [bokeh] Unhandled ERROR reply to 020852938CA94EAC868374171A265F0B: RuntimeError('Cannot apply patch to E0EFBC2CAC454F319C97899A5E36FB03 which is not in the document',)
t._handle_error @ session.js:85
t.handle @ session.js:27
t._steady_state_handler @ connection.js:275
ACK.t.msgtype._current_handler @ connection.js:256
t._on_message @ connection.js:217
t.socket.onmessage @ connection.js:67
session.js:85 [bokeh] Unhandled ERROR reply to 0DDF05BC974D4EBAB148667F0A4E39B6: RuntimeError('Cannot apply patch to E0EFBC2CAC454F319C97899A5E36FB03 which is not in the document',)
t._handle_error @ session.js:85
t.handle @ session.js:27
t._steady_state_handler @ connection.js:275
ACK.t.msgtype._current_handler @ connection.js:256
t._on_message @ connection.js:217
t.socket.onmessage @ connection.js:67
session.js:85 [bokeh] Unhandled ERROR reply to D9118580329C41078B9D18F5D79E7C56: RuntimeError('Cannot apply patch to E0EFBC2CAC454F319C97899A5E36FB03 which is not in the document',)
t._handle_error @ session.js:85
t.handle @ session.js:27
t._steady_state_handler @ connection.js:275
ACK.t.msgtype._current_handler @ connection.js:256
t._on_message @ connection.js:217
t.socket.onmessage @ connection.js:67
```

#### Screenshots or screencasts of the bug in action

![bokeh-application-google-chrome-4_3_2018-13_48_49](https://user-images.githubusercontent.com/844464/38266292-49edf67e-3746-11e8-8919-fb8f5dbb57df.gif)

I see similar errors referred to, e.g., #4810 and #4764, but they are marked closed. Is this potentially a regression? I hadn't noticed this before updating to 0.12.15.

**Comment by bryevdv** [comment]
@aliddell there are lots of ongoing issues with layout usage that is not fairly simple. Those issues closed very specific cases that happened to have a similar symptom. To be honest, I would describe dynamically adding and removing layout items as somewhat outside the original imagined scope of the bokeh server, but we will do what we can to stabilize and support these use cases if we are able. 

@mattpap I believe this is a dupe of another existing issue, but I'm not sure which one .

**Comment by mattpap** [comment]
It's almost definitively a duplicate, though let me into this, there may be some new cases being covered in this test code.

**Comment by aliddell** [comment]
Thanks

**Comment by bryevdv** [comment]
Interestingly enough this example does not involve removing anything, and also at least what is done here seems to function apart from the annoying message. In particular, the reset tool actually works on the JS side. It seems like the patch is failing to apply on the python side. Offhand, my speculation is that the `column` append is not collecting everything it should be collecting into `all_models` so the patch event seems to be for a model that doesn't exist. Alternatively there is some model created on the JS side that is not getting synced back properly, and that is what is trying to be patched.

**Comment by bryevdv** [comment]
This seems to have been fixed at some point, using the original code I cannot reproduce any errors on current `master` either in the shell or the js console:

<img width="1726" alt="screen shot 2018-05-10 at 12 28 36" src="https://user-images.githubusercontent.com/1078448/39889798-bb528888-544d-11e8-9aa2-928e3c1a9d4a.png">

If an issue persists please add additional information to reproduce and we can re-open.

**Comment by juanjaramillo** [comment]
Hi,
I'm still getting the same runtime error ('Cannot apply patch to which is not in the document anymore') as I am trying to update three plots every time someone moves one of the datasets. 
I am using MacOS High Sierra, latest python available. I think is worth taking a look at what I'm doing since I actually did what #7809 suggested, but still got the message. 

Here is the code (and the source - convert from xlsx to csv - ):

[input_1.xlsx](https://github.com/bokeh/bokeh/files/2418117/input_1.xlsx)

```
import pandas as pd
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import curdoc, show, output_notebook, output_file
from bokeh.models import ColumnDataSource, HoverTool, Panel, Tabs, CheckboxGroup, CategoricalColorMapper, Select, PointDrawTool, CustomJS 
from bokeh.models import DataTable, TableColumn, NumberFormatter, HTMLTemplateFormatter
from bokeh.layouts import row, column, gridplot, widgetbox
from bokeh.palettes import Spectral7
from bokeh.models.callbacks import CustomJS
from bokeh.client import push_session
# Import the data needed and make a list of category variables
sim_inicial = pd.read_csv('input_1.csv', sep = ";", index_col = 0)
initial_source = ColumnDataSource(sim_inicial)
empresas = list(sim_inicial['Empresa'].unique())
select = Select(title='Options', options=['Bi-G','A-G','Bi-D','A-D','Bi-E','A-E'], value='A-D')

def cal_stats(src,tiptec,tarifa):
    factor = 1.50
    temp_tipologia, temp_tecnologia = tiptec.split('-')
    sim_temp = src.to_df()
    sub_data = sim_temp[(sim_temp['Tipologia'] == temp_tipologia) & (sim_temp['Tecnologia'] == temp_tecnologia)]
    med = np.median(sub_data[tarifa])
    std = np.std(sub_data[tarifa])
    lim_inf = med-factor*std
    lim_sup = med+factor*std
    return med, lim_inf, lim_sup

def update_stats(src,idx_names):
    updated_stats = pd.DataFrame([cal_stats(src,'Bi-G','TMVT')+cal_stats(src,'Bi-G','TKMT')+cal_stats(src,'Bi-G','TOVT'),
        cal_stats(src,'A-G','TMVT')+cal_stats(src,'A-G','TKMT')+ cal_stats(src,'A-G','TOVT'),
        cal_stats(src,'Bi-D','TMVT')+ cal_stats(src,'Bi-D','TKMT')+ cal_stats(src,'Bi-D','TOVT'),
        cal_stats(src,'A-D','TMVT')+ cal_stats(src,'A-D','TKMT')+ cal_stats(src,'A-D','TOVT'),
        cal_stats(src,'Bi-E','TMVT')+ cal_stats(src,'Bi-E','TKMT')+ cal_stats(src,'Bi-E','TOVT'),
        cal_stats(src,'A-E','TMVT')+ cal_stats(src,'A-E','TKMT')+ cal_stats(src,'A-E','TOVT')],index=idx_names,columns=pd.MultiIndex.from_product([['TMVT','TKMT','TOVT'],['mediana','lim_inf','lim_sup']]))
    temp_src = ColumnDataSource(updated_stats)
    temp_core = temp_src.to_df().set_index('index')
    return temp_core

def restablish():
    snap_data = initial_source.to_df()
    initial_source.data = {'Lote': list(snap_data.Lote),'Tipologia': list(snap_data.Tipologia),'Tecnologia': list(snap_data.Tecnologia),
    'Empresa': list(snap_data.Empresa),'TMVT': list(snap_data.TMVT),'TKMT': list(snap_data.TKMT),'TOVT': list(snap_data.TOVT)}
    

tarifa_stats = update_stats(initial_source,select.options)
stats_source = ColumnDataSource(tarifa_stats)

mapper = CategoricalColorMapper(factors=empresas,palette=Spectral7)

def update_sources():
    initial_source.data.update(initial_source.data)
    stats_source.data.update(stats_source.data)

def makeplot(tiptec,tarifa,min_y,max_y,factor):

    helper = 'helper'

    # Example data
    temp_tipologia, temp_tecnologia = tiptec.split('-')
    sim_temp = initial_source.to_df()
    sub_data = sim_temp[(sim_temp['Tipologia'] == temp_tipologia) & (sim_temp['Tecnologia'] == temp_tecnologia)]
    sub_idx = sub_data.index.tolist()

    com_data = pd.concat([sim_temp,sub_data]).drop_duplicates(keep=False)   
    com_idx = com_data.index.tolist() 
    
    sim_temp.loc[sub_idx,helper] = 1
    sim_temp.loc[com_idx,helper] = -10

    initial_source.data.update(sim_temp.sort_index())

    # Create a blank figure with labels
    p1 = figure(plot_width = 450, plot_height = 400, 
               title = tarifa + ' de Proponentes',
               x_axis_label = 'Proponentes', y_axis_label = tarifa, x_range =(0,2), y_range = (min_y,max_y))
    p1.xaxis.visible = False
    p1.left[0].formatter.use_scientific = False

    # Add squares glyph
    renderer = p1.circle(helper, tarifa, source = initial_source, size = 12, color ={'field': 'Empresa', 'transform': mapper}, line_color=None,
             hover_fill_color='firebrick', hover_alpha=0.5,
             hover_line_color='white',name='points')

    # Create a HoverTool: hover
    draw_tool = PointDrawTool(renderers=[renderer], empty_value='')
    hover = HoverTool(tooltips=[('Empresa', '@Empresa'),('Lote','@Lote'),(tarifa, '@'+tarifa)],names = ['points'],mode='hline')
    p1.add_tools(hover,draw_tool)
    p1.toolbar.active_tap = draw_tool
    p1.toolbar.active_drag = draw_tool

    temp_stats = stats_source.to_df().set_index('index')
    s2 = ColumnDataSource(data=dict(xm=[1.25] * 3, ym=[temp_stats.loc[tiptec,tarifa+'_mediana'], temp_stats.loc[tiptec,tarifa+'_lim_inf'], temp_stats.loc[tiptec,tarifa+'_lim_sup']]))

    p1.line('xm', 'ym', source = s2, line_color='orange', line_width=2, line_dash='dashed')
    p1.circle('xm', 'ym', source = s2, fill_color='white', size=8, name = 'limits')
    
    initial_source.data.update(initial_source.data)
    s2.data.update(s2.data)


    return p1

p1 = makeplot(select.value,'TMVT',5000000,20000000,1.5)
p2 = makeplot(select.value,'TKMT',1000,4000,1.5)
p3 = makeplot(select.value,'TOVT',3000000,6000000,1.5)

# Define a callback function: callback
def callback(attr, old, new):

    layout.children[1].children[0] = makeplot(select.value,'TMVT',5000000,20000000,1.5)
    layout.children[1].children[1] = makeplot(select.value,'TKMT',1000,4000,1.5)
    layout.children[1].children[2] = makeplot(select.value,'TOVT',3000000,6000000,1.5)
    update_sources()

select.on_change('value', callback)

def on_change_data_source(attr, old, new):

    indices = list(range(len(old['helper'])))
    changes = [(i,j,k) for i,j,k in zip(indices, old['helper'], new['helper']) if j != k]
    if changes != []:
        for t in changes:
            idx = t[0]
            temp_data = initial_source.to_df()
            #Tarifas = {'TMVT':temp_data.loc[idx,'TMVT'],'TKMT':temp_data.loc[idx,'TKMT'],'TOVT':temp_data.loc[idx,'TOVT'],'TAS':temp_data.loc[idx,'TAS'],'Patios_temp':temp_data.loc[idx,'CTPatTemp']}
            #Tarifas_Modelo = {'TMVT':temp_data.loc[idx,'TMVT_modelo'],'TKMT':temp_data.loc[idx,'TKMT_modelo'],'TOVT':temp_data.loc[idx,'TOVT_modelo']}
            #costo_prov, costo_op, costo_tot, nueva_vpn_fcl = cl.actualizar_costos(initial_source.data['Tipologia'][idx],initial_source.data['Tecnologia'][idx],initial_source.data['Lote'][idx],initial_source.data['VPN_FCL_Modelo'][idx],2,Tarifas,Tarifas_Modelo)
            patch = {
                'TMVT':[(idx, initial_source.data['TMVT'][idx])],
                'TKMT':[(idx, initial_source.data['TKMT'][idx])],
                'TOVT':[(idx, initial_source.data['TOVT'][idx])]}

            initial_source.patch(patch)
            stats_source.data.update(ColumnDataSource(update_stats(initial_source,select.options)).data)
            layout.children[1].children[0] = makeplot(select.value,'TMVT',12000000,20000000,1.75)
            layout.children[1].children[1] = makeplot(select.value,'TKMT',1400,3000,1.25)
            layout.children[1].children[2] = makeplot(select.value,'TOVT',3500000,6000000,1.5)
        

initial_source.on_change('data', on_change_data_source)

layout = column(select,row(p1,p2,p3))
curdoc().add_next_tick_callback(on_change_data_source)
#ioloop.IOLoop.instance().add_callback(on_change_data_source)
curdoc().add_root(layout)
```

**Comment by andrewwaites** [comment]
FWIW, I was having this problem and managed to remove the error (annoying, not fatal) by changing how I updated a tabset of panels. I was updating 2 panels and the second update would trigger this error so I am thinking the first tabset update caused a regeneration of all tabs thus invalidating the second update. Anyway I changed from:
```
        sectorfig, sectorsource = make_fig(df, ticker_long)
        ftab = Panel(child=sectorfig, title="CEO Plots")
        
        tfig = make_trendFig(df, ticker_long)
        ttab = Panel(child=tfig, title="Sector Trend")
        
        layout.children[2].children[0].tabs[1] = ttab
        layout.children[2].children[0].tabs[2]= ftab
```
to...

```
        sectorfig, sectorsource = make_fig(df, ticker_long)
        tfig = make_trendFig(df, ticker_long)
        
        layout.children[2].children[0].tabs[1].child = tfig
        layout.children[2].children[0].tabs[2].child = sectorfig
```
and the error was removed.

**Comment by Dr-Nuke** [comment]
I still get the same error:

```
[...]
rev=bly.column(RevenuePlots()[0],revsliders,RevenuePlots()[1])
[...]
def updateRevPlotsFreq(attr, old, new):
    print(new)
    p.rev.freq=new
    print(rev.children[0])
    print(rev.children[2])
    revs,cumsums=RevenuePlots(t,p,p.rev.startdate,p.rev.enddate,p.rev.freq)
    rev.children[0]=revs
    print(rev.children[0])
    print(rev.children[2])
    rev.children[2]=cumsums
    print(rev.children[0])
    print(rev.children[2])
```
results in printed output

```
Figure(id='1276', ...)
Figure(id='1402', ...)
Figure(id='1545', ...)
Figure(id='1402', ...)
Figure(id='1545', ...)
Figure(id='1587', ...)
```

note how figure IDs one and two change once each
I tried the `.child` modificatino, but did not manage to create working syntax

**Comment by bryevdv** [comment]
The original code in the OP functions correctly (I just checked again) @Dr-Nuke  please make a new issue, with a *complete* reproduce and details.  (We cannot investigate anything we cannot run and reproduce)

**Comment by asartori86** [comment]
I encountered the same behavior. With these lines, I get the error message
```python
f1 = make_fig1()
f2 = make_fig2()

layout.children[1].children[0] = f1
layout.children[1].children[1] = f2
```

while if I update the layout as follows the warning disappears

```python
layout.children[1].children[0:2] = [f1,f2]
```
